#!/usr/bin/env bash
# update-bundle.sh — Export shareable KB entries and regenerate the catalog
#
# Usage:
#   ./shared/kb/update-bundle.sh
#
# What it does:
#   1. Runs `openclaw mc-kb export` to dump shareable entries to knowledge.json
#   2. Generates CATALOG.md — a human-readable index of what's in the bundle
#   3. Updates the catalog section in docs/mc-kb.md
#
# Commit both knowledge.json and the updated docs after running.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
BUNDLE="$SCRIPT_DIR/knowledge.json"
CATALOG="$SCRIPT_DIR/CATALOG.md"
DOCS_FILE="$REPO_DIR/docs/mc-kb.md"

echo "Exporting shareable KB entries..."
openclaw mc-kb export --out "$BUNDLE"

# Count entries
ENTRY_COUNT=$(python3 -c "import json; d=json.load(open('$BUNDLE')); print(len(d.get('entries',[])))")
echo "Bundle: $ENTRY_COUNT entries"

if [[ "$ENTRY_COUNT" -eq 0 ]]; then
  echo "No shareable entries found. Bundle is empty."
  cat > "$CATALOG" <<'EOF'
# Shared Knowledge Catalog

*No shareable entries yet.*
EOF
else
  # Generate CATALOG.md from the bundle
  python3 - "$BUNDLE" "$CATALOG" <<'PYEOF'
import json, sys
from datetime import datetime

bundle_path, catalog_path = sys.argv[1], sys.argv[2]
with open(bundle_path) as f:
    bundle = json.load(f)

entries = bundle.get("entries", [])
exported_at = bundle.get("exported_at", "unknown")

# Group by type
by_type = {}
for e in entries:
    t = e.get("type", "unknown")
    by_type.setdefault(t, []).append(e)

lines = [
    "# Shared Knowledge Catalog",
    "",
    f"**{len(entries)} entries** | Exported: {exported_at}",
    "",
    "This file is auto-generated by `update-bundle.sh`. Do not edit manually.",
    "",
]

type_order = ["fact", "workflow", "guide", "howto", "error", "postmortem", "lesson"]
for t in type_order:
    group = by_type.pop(t, [])
    if not group:
        continue
    lines.append(f"## {t.title()} ({len(group)})")
    lines.append("")
    for e in sorted(group, key=lambda x: x.get("title", "")):
        title = e.get("title", "Untitled")
        eid = e.get("id", "?")
        tags = ", ".join(e.get("tags", []))
        summary = e.get("summary", "")
        if not summary:
            content = e.get("content", "")
            summary = content[:120].replace("\n", " ")
            if len(content) > 120:
                summary += "..."
        line = f"- **{title}** (`{eid}`)"
        if tags:
            line += f" [{tags}]"
        lines.append(line)
        if summary:
            lines.append(f"  > {summary}")
    lines.append("")

# Any remaining types
for t, group in sorted(by_type.items()):
    lines.append(f"## {t.title()} ({len(group)})")
    lines.append("")
    for e in sorted(group, key=lambda x: x.get("title", "")):
        title = e.get("title", "Untitled")
        eid = e.get("id", "?")
        lines.append(f"- **{title}** (`{eid}`)")
    lines.append("")

with open(catalog_path, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Wrote {catalog_path}")
PYEOF
fi

# Update the inline catalog in docs/mc-kb.md
if [[ -f "$DOCS_FILE" ]]; then
  # Read the catalog content (without the h1 header)
  if [[ "$ENTRY_COUNT" -eq 0 ]]; then
    INLINE="*No entries yet. Run \`shared/kb/update-bundle.sh\` after marking entries as shareable.*"
  else
    # Extract everything after the first blank line in CATALOG.md (skip the h1)
    INLINE=$(python3 -c "
import sys
lines = open(sys.argv[1]).readlines()
# Skip h1 and first blank line
start = 0
for i, line in enumerate(lines):
    if i > 0 and line.strip() == '':
        start = i + 1
        break
print(''.join(lines[start:]).rstrip())
" "$CATALOG")
  fi

  # Replace content between markers
  python3 - "$DOCS_FILE" "$INLINE" <<'PYEOF'
import sys

docs_path = sys.argv[1]
inline = sys.argv[2]

with open(docs_path) as f:
    content = f.read()

start_marker = "<!-- KB_CATALOG_START -->"
end_marker = "<!-- KB_CATALOG_END -->"

start_idx = content.find(start_marker)
end_idx = content.find(end_marker)

if start_idx == -1 or end_idx == -1:
    print("Warning: catalog markers not found in docs/mc-kb.md")
    sys.exit(0)

new_content = (
    content[:start_idx + len(start_marker)]
    + "\n"
    + inline
    + "\n"
    + content[end_idx:]
)

with open(docs_path, "w") as f:
    f.write(new_content)

print(f"Updated inline catalog in {docs_path}")
PYEOF
fi

echo "Done. Commit knowledge.json, CATALOG.md, and docs/mc-kb.md."
